branch-defaults:
  main:
    environment: aws-eb-advanced-prod
    group_suffix: null
global:
  application_name: aws-eb-advanced
  branch: null
  default_region: eu-central-1
  profile: default
  repository: null
  workspace_type: Application
